{
    'title': {'type': 'string', 'valueString': 'Risotto alla lattuga e noci', 'content': 'Risotto alla lattuga e noci', 'boundingRegions': [{'pageNumber': 1, 'polygon': [625, 976, 1701, 890, 1719, 1118, 643, 1204]}], 'confidence': 0.958, 'spans': [{'offset': 0, 'length': 27}]}, 
    'category': {'type': 'string', 'valueString': 'RISOTTI', 'content': 'RISOTTI', 'boundingRegions': [{'pageNumber': 1, 'polygon': [1968, 1080, 2221, 1081, 2221, 1136, 1968, 1134]}], 'confidence': 0.546, 'spans': [{'offset': 895, 'length': 7}]}, 
    'prep_time': {'type': 'string', 'valueString': '15-20 min.', 'content': '15-20 min.', 'boundingRegions': [{'pageNumber': 1, 'polygon': [1978, 3281, 2257, 3265, 2260, 3315, 1981, 3331]}], 'confidence': 0.833, 'spans': [{'offset': 1230, 'length': 10}]}, 
    'difficulty': {'type': 'string', 'valueString': '· ·', 'content': '· ·', 'boundingRegions': [{'pageNumber': 1, 'polygon': [2271, 3319, 2329, 3316, 2332, 3370, 2274, 3373]}], 'confidence': 0.168, 'spans': [{'offset': 1253, 'length': 3}]}, 
    'description': {'type': 'string', 'valueString': "Lavate la lattuga e tagliatela a striscioline. Fate soffriggere la cipolla tritata finemente con il burro nella pentola a pressione aperta, unite lo speck tagliato a pezzetti, 1 cucchiaio di olio e fate rosolare bene.\n»Aggiungete la lattuga e proseguite la cottura per altri 2 minuti mescolando. ›Versate quindi il riso, fatevi sfumare il vino e lasciate insaporire mescolando. »Dopo qualche minuto, unite il brodo caldo, aggiustate di sale e chiudete la pentola. Quando la valvola inizia a fischiare, abbassate la fiamma e attendete 7 minuti.»Fate sfiatare il vapore poi mescolate bene, aggiungete il parmigiano, la ricotta fresca e i gherigli di noce precedentemente pestati con lo spicchio d'aglio.»Condite con sale e pepe ed eventualmente ancora un po' d'olio.»Rimestate delicatamente, e servite decorando con qualche fogliolina di prezzemolo spezzettata.", 'content': "Lavate la lattuga e tagliatela a striscioline. Fate soffriggere la cipolla tritata finemente con il burro nella pentola a pressione aperta, unite lo speck tagliato a pezzetti, 1 cucchiaio di olio e fate rosolare bene.\n»Aggiungete la lattuga e proseguite la cottura per altri 2 minuti mescolando. ›Versate quindi il riso, fatevi sfumare il vino e lasciate insaporire mescolando. »Dopo qualche minuto, unite il brodo caldo, aggiustate di sale e chiudete la pentola. Quando la valvola inizia a fischiare, abbassate la fiamma e attendete 7 minuti.»Fate sfiatare il vapore poi mescolate bene, aggiungete il parmigiano, la ricotta fresca e i gherigli di noce precedentemente pestati con lo spicchio d'aglio.»Condite con sale e pepe ed eventualmente ancora un po' d'olio.»Rimestate delicatamente, e servite decorando con qualche fogliolina di prezzemolo spezzettata.", 'boundingRegions': [{'pageNumber': 1, 'polygon': [611, 1334, 1807, 1306, 1849, 3057, 653, 3085]}], 'confidence': 0, 'spans': [{'offset': 28, 'length': 859}]}, 
    'ingredients': {'type': 'string', 'valueString': "ingredienti Riso Carnaroli, 350 g Speck tagliato grosso, 100 g Ricotta fresca, 60 g Gherigli di noce, 50 g Lattuga, 1 cespo Cipolla, 1 Aglio, 1 spicchio Parmigiano grattugiato Burro, 50 g Vino bianco secco, 1/2 bicchiere Brodo vegetale, 8 dl scarsi Prezzemolo, qualche foglia Olio extravergine d'oliva Sale, pepe", 'content': "ingredienti Riso Carnaroli, 350 g Speck tagliato grosso, 100 g Ricotta fresca, 60 g Gherigli di noce, 50 g Lattuga, 1 cespo Cipolla, 1 Aglio, 1 spicchio Parmigiano grattugiato Burro, 50 g Vino bianco secco, 1/2 bicchiere Brodo vegetale, 8 dl scarsi Prezzemolo, qualche foglia Olio extravergine d'oliva Sale, pepe", 'boundingRegions': [{'pageNumber': 1, 'polygon': [1924, 1483, 2458, 1478, 2470, 2899, 1937, 2904]}], 'confidence': 0, 'spans': [{'offset': 903, 'length': 312}]}, 
    'wine': {'type': 'string', 'valueString': 'Müller Thurgau', 'content': 'Müller Thurgau', 'boundingRegions': [{'pageNumber': 1, 'polygon': [1983, 3487, 2424, 3462, 2427, 3517, 1986, 3542]}], 'confidence': 0.819, 'spans': [{'offset': 1263, 'length': 14}]}
}

{
    
}